server:
  port: 8761

spring:
  application:
    name: service-discovery
  cloud:
    service-registry:
      auto-registration:
        enabled: false

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false